### ISSUE TITLE
Nice project!

### ISSUE THREAD

**Issue by mimooh** [arl/go-detour#21]
Hi! This code looks very elegant and I hope I'll be able to follow. My goal right now is to get the idea of the internals of navmeshing and the original Recast is perhaps more towards performance than education. So thanks a lot for the tool! Do you have any idea how it compares against Recast performance? Performance is not that crucial in my project, but I am curious.

**Comment by aurelien-rainone** [comment]
Hi Karol,

I wrote the tool mostly because with some friends we were developing a
multiplayer game where both server code and game logic were in go. We
required a navmesh for the pathfinding. I had discovered go recently and
thought it was a good exercise to port recast/detour, and also to learn
about navmesh generation and use, also there wasn't any similar library in
Go.

I didn't do any performance benchmark. Obviously it will be slower than the
original c version. For our use case though it was more than sufficient, we
were generating the navmesh offline, maps were static. At runtime we used
go-detour for pathfinding, it ran  concurrently to the rest of the game
logic and it wasn't the bottleneck of our game loop.

Cheers!

**Comment by mimooh** [comment]
Awesome! I am not concerned about the performance of go-recast that
much, as go-detour as this runs inside the main loop as I understand. So
you say it went smooth for you game, nice. We will be running crowd
simulations of hundreds of agents, and watch the results after the
simulation completes -- it doesn't need to be real time, but we will
have many queries (each agent will constantly make queries, right?).

It's a pleasure to read your code. Go seems nice and readable. Thanks a
lot for the educational aspect of this code!

> Hi Karol,
> 
> I wrote the tool mostly because with some friends we were developing a
> multiplayer game where both server code and game logic were in go. We
> required a navmesh for the pathfinding. I had discovered go recently and
> thought it was a good exercise to port recast/detour, and also to learn
> about navmesh generation and use, also there wasn't any similar library in
> Go.
> 
> I didn't do any performance benchmark. Obviously it will be slower than the
> original c version. For our use case though it was more than sufficient, we
> were generating the navmesh offline, maps were static. At runtime we used
> go-detour for pathfinding, it ran  concurrently to the rest of the game
> logic and it wasn't the bottleneck of our game loop.
> 
> Cheers!
>

**Comment by aurelien-rainone** [comment]
Go is a pleasure to write also! Nothing magic, nothing hidden, all is there
under your eyes.

FYI i implemented all of the original  detour and recast code related to
navmesh generation and pathfinding.
However the code related to crowd movement is missing ATM. We didn't need
it, but for the sake of completeness (with original code) I wanted to port
it.
You can find it in 'detour-crowd' branch of the repository as it hasn't
been merged.
The fact that you don't need real time is sure a good thing,
performance-wise. When you say each agent will constantly query, I'm not
sure what you mean exactly.
In the context of a crowd, you won't have each agent constantly query the
navmesh for global pathfinding, first it would be too heavy but overall
what you want is to handle a crowd (a group of agent having the same
destination) as one entity. Basically you consider the crowd as one entity
for global movement (going from A to B), and handle each entity separately
at the local level (going through doors, queuing, etc.)

Be aware that the detour-crowd is not-tested, probably not finished and
full of horrible bugs lurking ;-). You should report to the original
detour-crowd.
I would accept pull-request though :-)

**Comment by mimooh** [comment]
> Go is a pleasure to write also! Nothing magic, nothing hidden, all is there
> under your eyes.
It seems so!

> However the code related to crowd movement is missing ATM. We didn't need
> it, but for the sake of completeness (with original code) I wanted to port
I know that crowd module has issues. That's how I moved to Menge
https://github.com/MengeCrowdSim/Menge/issues/89 where I already
mentioned you solution :)

> In the context of a crowd, you won't have each agent constantly query the
> navmesh for global pathfinding, first it would be too heavy but overall
Depends on how long the initial group stays as a group throughout the
simulation, which I don't expect -- we are modeling evacuation under
fire and smoke conditions, people starting from the same location with
different pre-evacuation times, etc. It's reasonable what you say, to
treat the group as a single agent. We will see about it when we get
closer to it. Thanks once more!

**Comment by aurelien-rainone** [comment]
Ok very nice use case of pathfinding/navmesh!
Is this a personal or professional project? I'm just curious... :-)

About the fact that a crowd is treated as a single entity: it doesn't
always have to be. Treat a group of entities that are about to pass the
same door, from the same side, as a crowd for the duration of the
door-passing. In that way the crowd algorithm handles collisions, queuing
etc. Once the door has been passed, discard the crowd.

In that sense, the crowd is 'taking over' the entities it contains,
controls their movement. It is for you to decide when and how an entity is
part -or not- of a crowd, depending on the context.

**Comment by mimooh** [comment]
> Ok very nice use case of pathfinding/navmesh!
> Is this a personal or professional project? I'm just curious... :-)
I'd say Menge is a scientific project. It integrates the models of human
movement, the so called "local movement". Those models come right from
scientific papers, state of the art. RVO2, which Recast uses for crowds
is one of such models. In Menge, RVO2 is just one of the available
models.

I myself am a co-author of aamks system, which I'd also call scientific,
or maybe engineering.

-- 
Karol Kreński
tel. 517-302-055

> Ok very nice use case of pathfinding/navmesh!
> Is this a personal or professional project? I'm just curious... :-)
> 
> About the fact that a crowd is treated as a single entity: it doesn't
> always have to be. Treat a group of entities that are about to pass the
> same door, from the same side, as a crowd for the duration of the
> door-passing. In that way the crowd algorithm handles collisions, queuing
> etc. Once the door has been passed, discard the crowd.
> 
> In that sense, the crowd is 'taking over' the entities it contains,
> controls their movement. It is for you to decide when and how an entity is
> part -or not- of a crowd, depending on the context.
>

**Comment by mimooh** [comment]
> always have to be. Treat a group of entities that are about to pass the
> same door, from the same side, as a crowd for the duration of the
> door-passing. In that way the crowd algorithm handles collisions, queuing
> etc. Once the door has been passed, discard the crowd.
Very reasonable, thanks!

**Comment by mimooh** [comment]
So I have created navmesh.bin. Info gives me some details, but I wonder what's the verbose format of the navmesh. Can I see how the navemesh is really represented? Just curious :)

Also, if I change something in source, what's the command to compile? This far I have only used:
go get -u github.com/aurelien-rainone/go-detour/cmd/recast

**Comment by aurelien-rainone** [comment]
The navmesh is just a binary structure. If you want to see how it is built, this is done is one the sample in `sample/solomesh` or `sample/tilemesh` (check out the `Build` method). Search for `CreateNavMeshData`  and the `NavMeshCreateParams` structure.

To recompile, this is just the standard way, nothing fancy: `cd` to the project root and `go install ./...` will rebuild all the libraries and the `recast` cli tool, and place them into `$GOPATH/bin`

Happy hacking!

**Comment by mimooh** [comment]
In blender, unity, etc., navmesh has this polygons representation, so
I'd expect some vertices. Perhaps somewhere in the creation process
I could dump and visualize the navmesh?

-- 
Karol Kreński
tel. 517-302-055

**Comment by aurelien-rainone** [comment]
Oh ok i didn't understand you meant that. Yes you can visualize the navmesh
with the Graphical tool of the original C project Detour.

It's currently not possible to output the navmesh as an OBJ file, in fact a
navmesh contains more info than just the triangles it is made of. I reckon
it would be a nice addition to the project to output the navmesh as OBJ as
well to let the user visualize it.

2018-05-07 0:00 GMT+02:00 Karol Kreński <notifications@github.com>:

**Comment by mimooh** [comment]
Hi again! So how do I perform the actual query in detour? Say I am at x0,y0 and need to find my way to x1,y1?

**Comment by aurelien-rainone** [comment]
Hi,

The api is stricly the same as the one in the original cpp project and is honestly not very go idiomatic, a refactoring would be needed. 
So basically once you have loaded the nav mesh, you create a `detour.NavMeshQuery` and call the method that suits your needs best.

First you query the navmesh to obtain the polyref (polygon references) for your org and dest points, this is needed because the navmesh underlying algorithm manipulates polygon references. The function is `NavMeshQuery.FindNearestPoly`.

For an example, you can have a look at [path_test.go](https://github.com/aurelien-rainone/go-detour/blob/master/detour/path_test.go), function `TestFindPathFindStraightPath`.

The code seems complicated but most of it is boilerplate for navmesh loading, object and vector instantiation, error checking, etc..

You can find an example of use in an unfinished game project where go-detour is used as the pathfinder, Check out https://github.com/RookieGameDevs/surviveler/blob/go-detour-pathfinder/src/server/surviveler/pathfinder.go

**Comment by mimooh** [comment]
Aurelien, my main program is in python. I think of running go-detour as
a service/daemon. This service would have the navmesh in the memory and
would wait for my python queries: "src:x0,y0 dest:x1,y1" and would
return on its stdout the waypoints. Would go-detour allow for that?

-- 
Karol Kreński
tel. 517-302-055

**Comment by arl** [comment]
Sure it is possible. Actually recast and detour are libraries, recast is
consumed by the command line tool i provided in ./cmd for generating
navmesh files.
I guess your daemon would do the same.

Note: my username is now arl and not aurelien-rainone, please update your
hit remotes.

**Comment by mimooh** [comment]
Cannot grasp this go building. I at least managed to install the dependencies like cobra etc. and finally 'go install ./...' completes without errors, but I cannot figure out how to  build path_test.go - go install ignores this file. I went thru some docs/manuals but I just don't get the overall concept of the building process.

**Comment by arl** [comment]
Files ending with _test.go are ignored during normal building, they are
only compiled while running tests, with go test.
Have a look at
https://golang.org/cmd/go/#hdr-Compile_packages_and_dependencies

**Comment by mimooh** [comment]
Yeah, I was reading this before. Easier to read such docs, after you told me that _test.go is sensitive :) Thanks.

**Comment by mimooh** [comment]
Nope, this is killing me. Looks like I'd have to master go lang first and then cobra (judged by stepping thru cmd.Execute() ) to make even initial sense of it. And then I'd enter the world of some hex tagged internals of recast/detour... I have python/bash/php background, I can write / build simple go programs, since I went thru tutorial on their website, but this looks like entirely alien world. 

I tried with  path_test.go, but I don't know how to even start making it an application. If I had some rough initial setup and knew how to build it, then I could check these query functions. But I cannot even start.

I tried with surviveler/pathfinder.go. I downloaded the project and tried to grep for recast / detour keywords and there was nothing. How come?

I haven't tried the obvious yet -- to ask you to create such an app, would you? Is it much work?

**Comment by arl** [comment]
I'd say navmesh generation is not rocket science, nor it is exactly
trivial. The code would also surely be better off with more comments.
Look at https://github.com/RookieGameDevs/surviveler/pull/26, this is how I
used the library. The PR has not made it to master, because we stopped
working on the game and it has never been merged.

Anyway, remember this library is not production ready, it is a port of the
original C/C++ library. Binary files are compatible from one port to
another, and the basic functionality is there, but the API is probably more
documented, more efficient and you would find an existing community, even
if small, around the original project.
Writing such an app/lib takes an awful lot of time, time that I don't have,
but you would learn a lot along the way and would have a lot of fun, and
some minor headaches too...

**Comment by mimooh** [comment]
Oh, I misjudged it then. I thought it would be a couple of hours to write an app around this lib, but it's a lot of work and even headaches :) Thanks for all your help and I am closing this long issue now.

**Comment by arl** [comment]
You are welcome karol, thank you for your interest in go-detour!

Le mer. 4 juil. 2018 à 11:03, Karol Kreński <notifications@github.com> a
écrit :
