### ISSUE TITLE
Very nice project!

### ISSUE THREAD

**Issue by haoziAndy** [arl/go-detour#22]
My game client use unity3D to make game.I need use Navmesh from unity3D, I can?

**Comment by arl** [comment]
Detour uses its own navmesh format, the one generated by Recast. Though you
could use your own format with Detour, there may be quite a bit of glue
code to write, but in theory yes it's  possible.

**Comment by haoziAndy** [comment]
so I just use your Recast exported navmesh,your Detour can use it,right?
Now I have a Unity3D Navmesh data.Can i use your recast make from Unity3D navmesh to detour data?

**Comment by arl** [comment]
Navmesh created from recast is directly usable with detour. As I said though, if you currently have a unity 3d-made navmesh, there will be some code to write to convert from one format to another. For more info on how detour and recast work together, I suggest you to have a look at the original project (from which go-detour is a port), you will find the link in the README of go-detour.

**Comment by haoziAndy** [comment]
Thanks. So I can use Navmesh in detour if Unity3D Navmesh created from recast,right?

**Comment by haoziAndy** [comment]
Very Thanks. I understand completely.Now I have vertex information from unity3D,I use this  to created by recast navmesh,I can?

**Comment by arl** [comment]
Yes.

To sum up:

Recast is a tool that creates navigation meshes from level geometry.
Detour is a tool that lets you perform pathfinding and other kind of
queries over navmesh. It supports recast format out of the box.

**Comment by haoziAndy** [comment]
Very very very thanks.
