### ISSUE TITLE
FindNearestPoly returns and invalid polygon reference

### ISSUE THREAD

**Issue by pacarevolution** [arl/go-detour#31]
Hello! Me again! I think i'm close to finish implementing this on my server! So excited.

I'm having problems finding the nearest polygon to a point.
The point is (-113.73, -167.78, 240) and the navmesh data is this one [Mundo.zip](https://github.com/arl/go-detour/files/6650844/Mundo.zip)

I'm using this code:

`var Query *detour.NavMeshQuery
var Filter detour.QueryFilter
var Polygon detour.PolyRef
var ProjectedPoint d3.Vec3
var Status detour.Status
Extent := d3.NewVec3XYZ(5,5,5)
Point := d3.NewVec3XYZ(-113.73,-167.78,240)
Status, Query = detour.NewNavMeshQuery(NavMesh, 1000)
Filter = detour.NewStandardQueryFilter()
Status, Polygon, ProjectedPoint = Query.FindNearestPoly(Point, Extent, Filter)`

Then when I try NavMesh.IsValidPolyRef(Polygon) it always throws false.
I tried with different Extent values (like really big ones) and the result is always the same.

Any clues on what I might be doing wrong?
Thankss

**Comment by arl** [comment]
You should test the status of each function call that return a status with `detour.StatusFailed(st)` (and friends).

**Comment by pacarevolution** [comment]
Yess. That's exactly what I did. Here's a more detailed view from the code:
![Sin título](https://user-images.githubusercontent.com/46936924/121953601-23f22f80-cd34-11eb-8338-d36cf5a37001.png)

All status are OK, even FindNearestPoly returns success! But as the function description says, it might return success but the search box doesn't intersect any polygons apparently.

I tried a lot of different points and extents and still can't find a valid polygon.

**Comment by arl** [comment]
Ok. I vaguely remember having experienced this years ago while I was writing tests. I honestly don't remember how I've solved it though. Try loading the navmesh used in tests, if that works and you can perform queries on it with your code, then the problem might come from the navmesh.

**Comment by pacarevolution** [comment]
Yea it seems it's a problem with the navmesh export module! I'm looking into it. Thankss!

**Comment by arl** [comment]
@pacarevolution just so you know, i've tagged a new release and fixed the problematic license file, so now you can browse the package documentation from https://pkg.go.dev/github.com/arl/go-detour. Cheers!
